version: '3.9'
services:
  app:
    image: phinixhq/socks-http-proxy-exporter
    restart: unless-stopped
    environment: 
      AXIOS_TIMEOUT: "8000"
      HTTP_PROXY_TIMEOUT: "8000"
      SOCKS_PROXY_TIMEOUT: "8000"
      SENTRY_DSN:
      SCOPE:
    network_mode: "host"
